name: Mirror repo

on:
  workflow_call:
    inputs:
      GITLAB_URL:
        required: true
        type: string
#    secrets:
#      GITLAB_USER:
#        required: true
#      GITLAB_PASSWORD:
#        required: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: ${{ inputs.GITLAB_URL }}
          GIT_USERNAME: ${{ secrets.GITLAB_USER }}
          GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
